[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/gunicorn config.wsgi --log-file -"