# Generated by Django 5.2.1 on 2026-05-19 19:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pos_x', models.FloatField(default=50.0, help_text='Posición X en % sobre la imagen satelital')),
                ('pos_y', models.FloatField(default=50.0, help_text='Posición Y en % sobre la imagen satelital')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Checkpoint',
                'verbose_name_plural': 'Checkpoints',
                'ordering': ['instalacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_satelital', models.ImageField(blank=True, null=True, upload_to='instalaciones/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionRonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('completada', 'Completada'), ('incompleta', 'Incompleta')], default='en_curso', max_length=20)),
                ('vigilante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejecución de Ronda',
                'verbose_name_plural': 'Ejecuciones de Rondas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('timestamp_servidor', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('observacion', 'Observación'), ('incidencia', 'Incidencia'), ('alarma', 'Alarma')], default='observacion', max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('atendida', models.BooleanField(default=False)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='rondines.checkpoint')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='rondines.ejecucionronda')),
            ],
            options={
                'verbose_name': 'Scan de Checkpoint',
                'verbose_name_plural': 'Scans de Checkpoints',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='instalacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='rondines.instalacion'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('vigilante', 'Vigilante'), ('supervisor', 'Supervisor')], default='vigilante', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='rondines.instalacion')),
                ('vigilantes_asignados', models.ManyToManyField(blank=True, help_text='Si vacío, todos los vigilantes pueden ejecutarla', related_name='rondas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ronda',
                'verbose_name_plural': 'Rondas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ejecucionronda',
            name='ronda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='rondines.ronda'),
        ),
        migrations.CreateModel(
            name='RondaCheckpointOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rondines.checkpoint')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rondines.ronda')),
            ],
            options={
                'verbose_name': 'Orden de Checkpoint en Ronda',
                'verbose_name_plural': 'Órdenes de Checkpoints en Rondas',
                'ordering': ['orden'],
                'unique_together': {('ronda', 'checkpoint')},
            },
        ),
        migrations.AddField(
            model_name='ronda',
            name='checkpoints',
            field=models.ManyToManyField(related_name='rondas', through='rondines.RondaCheckpointOrden', to='rondines.checkpoint'),
        ),
    ]
